spring:
  application:
    name: capstone-workbook

  profiles:
    active: local
    group:
      "local": "local"
      "dev": "dev"

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB